/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppRoot {}
  interface Step1 {}
}

declare global {


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLStep1Element extends Components.Step1, HTMLStencilElement {}
  var HTMLStep1Element: {
    prototype: HTMLStep1Element;
    new (): HTMLStep1Element;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'step-1': HTMLStep1Element;
  }
}

declare namespace LocalJSX {
  interface AppRoot {}
  interface Step1 {}

  interface IntrinsicElements {
    'app-root': AppRoot;
    'step-1': Step1;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'step-1': LocalJSX.Step1 & JSXBase.HTMLAttributes<HTMLStep1Element>;
    }
  }
}


