/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  RouterHistory,
} from '@stencil/router';

export namespace Components {
  interface AppRoot {}
  interface CLogoutBtn {
    'history': RouterHistory;
  }
  interface PCatchall {}
  interface PDashboard {}
  interface PHome {}
  interface PLogin {}
  interface PRegister {
    'history': RouterHistory;
  }
  interface PSettings {}
}

declare global {


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLCLogoutBtnElement extends Components.CLogoutBtn, HTMLStencilElement {}
  var HTMLCLogoutBtnElement: {
    prototype: HTMLCLogoutBtnElement;
    new (): HTMLCLogoutBtnElement;
  };

  interface HTMLPCatchallElement extends Components.PCatchall, HTMLStencilElement {}
  var HTMLPCatchallElement: {
    prototype: HTMLPCatchallElement;
    new (): HTMLPCatchallElement;
  };

  interface HTMLPDashboardElement extends Components.PDashboard, HTMLStencilElement {}
  var HTMLPDashboardElement: {
    prototype: HTMLPDashboardElement;
    new (): HTMLPDashboardElement;
  };

  interface HTMLPHomeElement extends Components.PHome, HTMLStencilElement {}
  var HTMLPHomeElement: {
    prototype: HTMLPHomeElement;
    new (): HTMLPHomeElement;
  };

  interface HTMLPLoginElement extends Components.PLogin, HTMLStencilElement {}
  var HTMLPLoginElement: {
    prototype: HTMLPLoginElement;
    new (): HTMLPLoginElement;
  };

  interface HTMLPRegisterElement extends Components.PRegister, HTMLStencilElement {}
  var HTMLPRegisterElement: {
    prototype: HTMLPRegisterElement;
    new (): HTMLPRegisterElement;
  };

  interface HTMLPSettingsElement extends Components.PSettings, HTMLStencilElement {}
  var HTMLPSettingsElement: {
    prototype: HTMLPSettingsElement;
    new (): HTMLPSettingsElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'c-logout-btn': HTMLCLogoutBtnElement;
    'p-catchall': HTMLPCatchallElement;
    'p-dashboard': HTMLPDashboardElement;
    'p-home': HTMLPHomeElement;
    'p-login': HTMLPLoginElement;
    'p-register': HTMLPRegisterElement;
    'p-settings': HTMLPSettingsElement;
  }
}

declare namespace LocalJSX {
  interface AppRoot {}
  interface CLogoutBtn {
    'history'?: RouterHistory;
  }
  interface PCatchall {}
  interface PDashboard {}
  interface PHome {}
  interface PLogin {}
  interface PRegister {
    'history'?: RouterHistory;
  }
  interface PSettings {}

  interface IntrinsicElements {
    'app-root': AppRoot;
    'c-logout-btn': CLogoutBtn;
    'p-catchall': PCatchall;
    'p-dashboard': PDashboard;
    'p-home': PHome;
    'p-login': PLogin;
    'p-register': PRegister;
    'p-settings': PSettings;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'c-logout-btn': LocalJSX.CLogoutBtn & JSXBase.HTMLAttributes<HTMLCLogoutBtnElement>;
      'p-catchall': LocalJSX.PCatchall & JSXBase.HTMLAttributes<HTMLPCatchallElement>;
      'p-dashboard': LocalJSX.PDashboard & JSXBase.HTMLAttributes<HTMLPDashboardElement>;
      'p-home': LocalJSX.PHome & JSXBase.HTMLAttributes<HTMLPHomeElement>;
      'p-login': LocalJSX.PLogin & JSXBase.HTMLAttributes<HTMLPLoginElement>;
      'p-register': LocalJSX.PRegister & JSXBase.HTMLAttributes<HTMLPRegisterElement>;
      'p-settings': LocalJSX.PSettings & JSXBase.HTMLAttributes<HTMLPSettingsElement>;
    }
  }
}


